//! Cross-checks the authored V31 profile against the machine-parsed address map
//! (profiles/maps/roland-v31-address-map.json, generated by
//! tools/parse_midi_impl.py from Roland's MIDI Implementation).
//!
//! Every profile parameter carries a `doc` provenance ref ("Block/Param Name");
//! this test verifies its offset, length, encoding, range, labels, and repeat
//! dimensions byte-for-byte against the parsed doc — hand-typed profile facts
//! can't silently drift from the vendor documentation.

use device::{DeviceProfile, ProfileRegistry};
use serde_json::Value;
use sysex::Encoding;

const MAP_JSON: &str = include_str!(concat!(
    env!("WORKSPACE_DIR"),
    "/profiles/maps/roland-v31-address-map.json"
));

/// Kit-area param id prefix → the child entry inside the map's [Kit] container
/// that anchors it (first instance for repeated groups).
const KIT_ANCHORS: &[(&str, &str)] = &[
    ("kit.common.", "Kit Common"),
    ("kit.unit.common.", "Kit Unit Common"),
    ("kit.unit.layer.", "Kit Unit LayerA"),
    ("kit.pad.", "Kit Pad"),
    ("kit.fx.", "Kit FX"),
    ("kit.overhead.", "Kit Overhead"),
    ("kit.room.", "Kit Room"),
    ("kit.reverb.", "Kit Reverb"),
];

fn linear(bytes: &[Value]) -> u64 {
    bytes
        .iter()
        .fold(0u64, |acc, b| (acc << 7) | b.as_u64().unwrap())
}

fn linear_u8(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0u64, |acc, &b| (acc << 7) | u64::from(b))
}

fn v31() -> DeviceProfile {
    ProfileRegistry::with_builtin()
        .match_model(&[1, 6, 1])
        .expect("built-in V31 profile")
        .clone()
}

fn map() -> Value {
    serde_json::from_str(MAP_JSON).expect("valid address map JSON")
}

fn map_param<'a>(map: &'a Value, block: &str, name: &str) -> &'a Value {
    map["blocks"][block]["params"]
        .as_array()
        .unwrap_or_else(|| panic!("no leaf block [{block}] in the map"))
        .iter()
        .find(|p| p["name"] == name)
        .unwrap_or_else(|| panic!("no param {name:?} in map block [{block}]"))
}

fn kit_child<'a>(map: &'a Value, name: &str) -> &'a Value {
    map["blocks"]["Kit"]["children"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == name)
        .unwrap_or_else(|| panic!("no child {name:?} in map block [Kit]"))
}

#[test]
fn areas_match_the_top_level_map() {
    let p = v31();
    let m = map();
    let top = m["top_level"].as_array().unwrap();

    let kit = top.iter().find(|e| e["block"] == "Kit").unwrap();
    let area = &p.areas["kit"];
    assert_eq!(
        linear_u8(&area.address),
        linear(kit["address"].as_array().unwrap())
    );
    assert_eq!(
        linear_u8(&area.stride.unwrap()),
        linear(kit["stride"].as_array().unwrap())
    );
    assert_eq!(area.count, kit["count"].as_u64().map(|c| c as u32));

    let current = top.iter().find(|e| e["block"] == "Current").unwrap();
    assert_eq!(
        linear_u8(&p.areas["current"].address),
        linear(current["address"].as_array().unwrap())
    );
}

#[test]
fn every_parameter_matches_its_doc_ref() {
    let p = v31();
    let m = map();

    for param in &p.parameters {
        let doc = param
            .doc
            .as_ref()
            .unwrap_or_else(|| panic!("{}: missing doc provenance ref", param.id));
        let (block, name) = doc.split_once('/').expect("doc is Block/Name");
        let mp = map_param(&m, block, name);

        // Size.
        assert_eq!(
            param.len,
            mp["len"].as_u64().unwrap() as usize,
            "{}: len differs from the doc",
            param.id
        );

        // Encoding: the map doesn't know signedness, so a doc "nibble" is our
        // nibble (range ≥ 0) or signed_nibble (range < 0).
        let doc_min = mp["range"][0].as_i64();
        match mp["encoding"].as_str().unwrap() {
            "plain7" => assert_eq!(param.encoding, Encoding::Plain7, "{}", param.id),
            "ascii" => assert_eq!(param.encoding, Encoding::Ascii, "{}", param.id),
            "nibble" => {
                let expect = if doc_min.is_some_and(|v| v < 0) {
                    Encoding::SignedNibble
                } else {
                    Encoding::Nibble
                };
                assert_eq!(param.encoding, expect, "{}", param.id);
            }
            other => panic!("{}: unexpected map encoding {other}", param.id),
        }

        // Range (open doc ranges like "Instrument (0 - )" stay open in the
        // profile). For ASCII the doc range is per character — not a string
        // constraint, so it isn't mirrored.
        match (
            param.range.filter(|_| param.encoding != Encoding::Ascii),
            mp["range"]
                .as_array()
                .filter(|_| param.encoding != Encoding::Ascii),
        ) {
            (Some(r), Some(dr)) => {
                assert_eq!(Some(r.min), dr[0].as_i64(), "{}: range min", param.id);
                assert_eq!(
                    Some(r.max),
                    dr[1].as_i64(),
                    "{}: range max (open doc range ⇒ omit range in the profile)",
                    param.id
                );
            }
            (None, Some(dr)) => assert!(
                dr[1].is_null(),
                "{}: the doc has a closed range, the profile must carry it",
                param.id
            ),
            (None, None) => {}
            (Some(_), None) => panic!("{}: range invented — the doc has none", param.id),
        }

        // Labels, when the profile carries them, must be the doc's value list.
        if let Some(labels) = &param.labels {
            let display = mp["display"]
                .as_array()
                .unwrap_or_else(|| panic!("{}: labels but no doc value list", param.id))
                .iter()
                .map(|l| l.as_str().unwrap())
                .collect::<Vec<_>>()
                .join(" ");
            let doc_labels: Vec<String> =
                display.split(',').map(|s| s.trim().to_string()).collect();
            assert_eq!(
                labels, &doc_labels,
                "{}: labels differ from the doc",
                param.id
            );
            let span = param.range.expect("labels imply a closed range");
            assert_eq!(
                labels.len() as i64,
                span.max - span.min + 1,
                "{}: one label per raw value",
                param.id
            );
        }

        // Absolute address at index 0 (and the dim grid below).
        let expected = match param.area.as_str() {
            "current" => linear(mp["offset"].as_array().unwrap()),
            "kit" => {
                let anchor = KIT_ANCHORS
                    .iter()
                    .find(|(prefix, _)| param.id.starts_with(prefix))
                    .unwrap_or_else(|| panic!("{}: no kit anchor known", param.id))
                    .1;
                let child = kit_child(&m, anchor);
                linear_u8(&p.areas["kit"].address)
                    + linear(child["address"].as_array().unwrap())
                    + linear(mp["offset"].as_array().unwrap())
            }
            other => panic!("{}: unexpected area {other}", param.id),
        };
        let zeros = vec![0u32; 1 + param.dims.len()];
        let got = p
            .address_of(&param.id, &zeros)
            .unwrap_or_else(|| panic!("{}: address_of failed", param.id));
        assert_eq!(
            linear_u8(&got),
            expected,
            "{}: absolute address differs from the doc",
            param.id
        );

        // Repeat dimensions vs the doc's repeated child entries.
        for dim in &param.dims {
            match dim.name.as_str() {
                // The innermost repeat is the anchored child group itself.
                "unit" | "pad" | "fx" => {
                    let anchor = KIT_ANCHORS
                        .iter()
                        .find(|(prefix, _)| param.id.starts_with(prefix))
                        .unwrap()
                        .1;
                    let child = kit_child(&m, anchor);
                    assert_eq!(
                        u64::from(dim.count),
                        child["count"].as_u64().unwrap(),
                        "{}: dim {} count",
                        param.id,
                        dim.name
                    );
                    assert_eq!(
                        linear_u8(&dim.stride),
                        linear(child["stride"].as_array().unwrap()),
                        "{}: dim {} stride",
                        param.id,
                        dim.name
                    );
                }
                // Layers are separate named groups; the stride is A→B, and C
                // must sit exactly one more stride further.
                "layer" => {
                    let a = linear(
                        kit_child(&m, "Kit Unit LayerA")["address"]
                            .as_array()
                            .unwrap(),
                    );
                    let b = linear(
                        kit_child(&m, "Kit Unit LayerB")["address"]
                            .as_array()
                            .unwrap(),
                    );
                    let c = linear(
                        kit_child(&m, "Kit Unit LayerC")["address"]
                            .as_array()
                            .unwrap(),
                    );
                    assert_eq!(dim.count, 3, "{}: layer count", param.id);
                    assert_eq!(linear_u8(&dim.stride), b - a, "{}: layer stride", param.id);
                    assert_eq!(c - b, b - a, "layer grid must be uniform");
                }
                other => panic!("{}: unknown dim {other}", param.id),
            }
        }
    }
}

#[test]
fn sub_name_is_64_chars_per_the_doc() {
    // The original hand-authored profile said 16; the parsed doc says 64.
    let p = v31();
    assert_eq!(p.parameter("kit.common.sub_name").unwrap().len, 64);
}
