//! Cross-checks each authored profile against its machine-parsed address map
//! (profiles/maps/*-address-map.json, generated by tools/parse_midi_impl.py from
//! Roland's MIDI Implementation).
//!
//! Every profile parameter carries a `doc` provenance ref ("Block/Param Name");
//! this test verifies its offset, length, encoding, range, labels, and repeat
//! dimensions byte-for-byte against the parsed doc — hand-typed profile facts
//! can't silently drift from the vendor documentation. The same checks run for
//! every built-in profile: a module we have not met is held to the documents at
//! least as strictly as one we have.

use device::{DeviceProfile, ProfileRegistry};
use serde_json::Value;
use sysex::Encoding;

/// One profile and the map it must agree with.
struct Target {
    model_id: &'static [u8],
    map_json: &'static str,
    /// Kit-area param id prefix → the child entry inside the map's [Kit]
    /// container that anchors it (first instance for repeated groups).
    kit_anchors: &'static [(&'static str, &'static str)],
    /// The [Kit] children that are one instrument layer each, in layer order:
    /// the `layer` dim must count them and step from the first to the second.
    layer_groups: &'static [&'static str],
    /// How many named floors (`-INF`, `END`) the profile is known to carry — a
    /// floor against a profile quietly losing its sentinels.
    min_sentinels: usize,
    /// How many `catalog` bindings the profile is known to carry.
    min_catalog_bindings: usize,
}

const TARGETS: &[Target] = &[
    Target {
        model_id: &[1, 6, 1],
        map_json: include_str!(concat!(
            env!("WORKSPACE_DIR"),
            "/profiles/maps/roland-v31-address-map.json"
        )),
        kit_anchors: &[
            ("kit.common.", "Kit Common"),
            ("kit.unit.common.", "Kit Unit Common"),
            ("kit.unit.layer.", "Kit Unit LayerA"),
            ("kit.pad.", "Kit Pad"),
            ("kit.fx.", "Kit FX"),
            ("kit.overhead.", "Kit Overhead"),
            ("kit.room.", "Kit Room"),
            ("kit.reverb.", "Kit Reverb"),
        ],
        layer_groups: &["Kit Unit LayerA", "Kit Unit LayerB", "Kit Unit LayerC"],
        // Nine dB levels and the set-list step.
        min_sentinels: 10,
        // The instrument and the FX type.
        min_catalog_bindings: 2,
    },
    Target {
        model_id: &[0, 0, 0, 0x4B],
        map_json: include_str!(concat!(
            env!("WORKSPACE_DIR"),
            "/profiles/maps/roland-td-17-address-map.json"
        )),
        kit_anchors: &[
            ("kit.common.", "Kit Common"),
            ("kit.unit.common.", "Kit Unit Common"),
            ("kit.unit.layer.", "Kit Unit Main"),
            ("kit.mfx.", "Kit Multi FX"),
            ("kit.ambience.", "Kit Ambience"),
            ("kit.reverb.", "Kit Reverb"),
        ],
        layer_groups: &["Kit Unit Main", "Kit Unit Sub"],
        // Eight dB levels.
        min_sentinels: 8,
        // No catalogs yet (TASKS: "TD-17 catalogs").
        min_catalog_bindings: 0,
    },
];

fn linear(bytes: &[Value]) -> u64 {
    bytes
        .iter()
        .fold(0u64, |acc, b| (acc << 7) | b.as_u64().unwrap())
}

fn linear_u8(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0u64, |acc, &b| (acc << 7) | u64::from(b))
}

fn profile_of(t: &Target) -> DeviceProfile {
    ProfileRegistry::with_builtin()
        .match_model(t.model_id)
        .unwrap_or_else(|| panic!("no built-in profile for model {:?}", t.model_id))
        .clone()
}

fn map_of(t: &Target) -> Value {
    serde_json::from_str(t.map_json).expect("valid address map JSON")
}

fn map_param<'a>(map: &'a Value, block: &str, name: &str) -> &'a Value {
    map["blocks"][block]["params"]
        .as_array()
        .unwrap_or_else(|| panic!("no leaf block [{block}] in the map"))
        .iter()
        .find(|p| p["name"] == name)
        .unwrap_or_else(|| panic!("no param {name:?} in map block [{block}]"))
}

fn kit_child<'a>(map: &'a Value, name: &str) -> &'a Value {
    map["blocks"]["Kit"]["children"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == name)
        .unwrap_or_else(|| panic!("no child {name:?} in map block [Kit]"))
}

fn kit_anchor<'a>(t: &'a Target, param_id: &str) -> &'a str {
    t.kit_anchors
        .iter()
        .find(|(prefix, _)| param_id.starts_with(prefix))
        .unwrap_or_else(|| panic!("{param_id}: no kit anchor known"))
        .1
}

#[test]
fn areas_match_the_top_level_map() {
    for t in TARGETS {
        let p = profile_of(t);
        let m = map_of(t);
        let top = m["top_level"].as_array().unwrap();

        let kit = top.iter().find(|e| e["block"] == "Kit").unwrap();
        let area = &p.areas["kit"];
        assert_eq!(
            linear_u8(&area.address),
            linear(kit["address"].as_array().unwrap()),
            "{}: kit area",
            p.profile_id
        );
        assert_eq!(
            linear_u8(&area.stride.unwrap()),
            linear(kit["stride"].as_array().unwrap()),
            "{}: kit stride",
            p.profile_id
        );
        assert_eq!(
            area.count,
            kit["count"].as_u64().map(|c| c as u32),
            "{}: kit count",
            p.profile_id
        );

        let current = top.iter().find(|e| e["block"] == "Current").unwrap();
        assert_eq!(
            linear_u8(&p.areas["current"].address),
            linear(current["address"].as_array().unwrap()),
            "{}: current area",
            p.profile_id
        );

        // Set lists exist on the V31 only; a profile that declares the area
        // must agree with the doc, one that doesn't must have no doc for it.
        let setlist = top.iter().find(|e| e["block"] == "SetListParams");
        match (p.areas.get("setlist"), setlist) {
            (Some(area), Some(setlist)) => {
                assert_eq!(
                    linear_u8(&area.address),
                    linear(setlist["address"].as_array().unwrap())
                );
                assert_eq!(
                    linear_u8(&area.stride.unwrap()),
                    linear(setlist["stride"].as_array().unwrap())
                );
                assert_eq!(area.count, setlist["count"].as_u64().map(|c| c as u32));
            }
            (None, None) => {}
            (profile, doc) => panic!(
                "{}: set lists in the profile ({}) and the doc ({}) disagree",
                p.profile_id,
                profile.is_some(),
                doc.is_some()
            ),
        }
    }
}

#[test]
fn every_parameter_matches_its_doc_ref() {
    for t in TARGETS {
        let p = profile_of(t);
        let m = map_of(t);
        for param in &p.parameters {
            check_param(t, &p, &m, param);
        }
    }
}

fn check_param(t: &Target, p: &DeviceProfile, m: &Value, param: &device::ParameterDef) {
    let doc = param
        .doc
        .as_ref()
        .unwrap_or_else(|| panic!("{}: missing doc provenance ref", param.id));
    let (block, name) = doc.split_once('/').expect("doc is Block/Name");
    let mp = map_param(m, block, name);

    // Size.
    assert_eq!(
        param.len,
        mp["len"].as_u64().unwrap() as usize,
        "{}: len differs from the doc",
        param.id
    );

    // Encoding: the map doesn't know signedness, so a doc "nibble" is our
    // nibble (range ≥ 0) or signed_nibble (range < 0).
    let doc_min = mp["range"][0].as_i64();
    match mp["encoding"].as_str().unwrap() {
        "plain7" => assert_eq!(param.encoding, Encoding::Plain7, "{}", param.id),
        // The doc distinguishes the two ASCII packings by how many bytes a
        // character occupies (`bytes_per_char: 2` = a nibble pair each).
        "ascii" => {
            let expect = if mp["bytes_per_char"].as_u64() == Some(2) {
                Encoding::AsciiNibble
            } else {
                Encoding::Ascii
            };
            assert_eq!(param.encoding, expect, "{}", param.id);
        }
        "nibble" => {
            let expect = if doc_min.is_some_and(|v| v < 0) {
                Encoding::SignedNibble
            } else {
                Encoding::Nibble
            };
            assert_eq!(param.encoding, expect, "{}", param.id);
        }
        other => panic!("{}: unexpected map encoding {other}", param.id),
    }

    // Range (open doc ranges like "Instrument (0 - )" stay open in the
    // profile). For ASCII the doc range is per character — not a string
    // constraint, so it isn't mirrored.
    match (
        param.range.filter(|_| !param.encoding.is_text()),
        mp["range"].as_array().filter(|_| !param.encoding.is_text()),
    ) {
        (Some(r), Some(dr)) => {
            assert_eq!(Some(r.min), dr[0].as_i64(), "{}: range min", param.id);
            assert_eq!(
                Some(r.max),
                dr[1].as_i64(),
                "{}: range max (open doc range ⇒ omit range in the profile)",
                param.id
            );
        }
        (None, Some(dr)) => assert!(
            dr[1].is_null(),
            "{}: the doc has a closed range, the profile must carry it",
            param.id
        ),
        (None, None) => {}
        (Some(_), None) => panic!("{}: range invented — the doc has none", param.id),
    }

    // Labels, when the profile carries them, must be the doc's value list.
    if let Some(labels) = &param.labels {
        let display = mp["display"]
            .as_array()
            .unwrap_or_else(|| panic!("{}: labels but no doc value list", param.id))
            .iter()
            .map(|l| l.as_str().unwrap())
            .collect::<Vec<_>>()
            .join(" ");
        let doc_labels: Vec<String> = display.split(',').map(|s| s.trim().to_string()).collect();
        assert_eq!(
            labels, &doc_labels,
            "{}: labels differ from the doc",
            param.id
        );
        let span = param.range.expect("labels imply a closed range");
        assert_eq!(
            labels.len() as i64,
            span.max - span.min + 1,
            "{}: one label per raw value",
            param.id
        );
    }

    // Absolute address at index 0 (and the dim grid below).
    let expected = match param.area.as_str() {
        "current" => linear(mp["offset"].as_array().unwrap()),
        "setlist" => {
            linear_u8(&p.areas["setlist"].address) + linear(mp["offset"].as_array().unwrap())
        }
        "kit" => {
            let child = kit_child(m, kit_anchor(t, &param.id));
            linear_u8(&p.areas["kit"].address)
                + linear(child["address"].as_array().unwrap())
                + linear(mp["offset"].as_array().unwrap())
        }
        other => panic!("{}: unexpected area {other}", param.id),
    };
    let zeros = vec![0u32; 1 + param.dims.len()];
    let got = p
        .address_of(&param.id, &zeros)
        .unwrap_or_else(|| panic!("{}: address_of failed", param.id));
    assert_eq!(
        linear_u8(&got),
        expected,
        "{}: absolute address differs from the doc",
        param.id
    );

    // Repeat dimensions vs the doc's repeated child entries.
    for dim in &param.dims {
        match dim.name.as_str() {
            // The innermost repeat is the anchored child group itself.
            "unit" | "pad" | "fx" => {
                let child = kit_child(m, kit_anchor(t, &param.id));
                assert_eq!(
                    u64::from(dim.count),
                    child["count"].as_u64().unwrap(),
                    "{}: dim {} count",
                    param.id,
                    dim.name
                );
                assert_eq!(
                    linear_u8(&dim.stride),
                    linear(child["stride"].as_array().unwrap()),
                    "{}: dim {} stride",
                    param.id,
                    dim.name
                );
            }
            // Layers are separate named groups; the stride is first→second,
            // and every further group must sit exactly one more stride on.
            "layer" => {
                let starts: Vec<u64> = t
                    .layer_groups
                    .iter()
                    .map(|g| linear(kit_child(m, g)["address"].as_array().unwrap()))
                    .collect();
                assert_eq!(
                    dim.count as usize,
                    starts.len(),
                    "{}: layer count",
                    param.id
                );
                let stride = starts[1] - starts[0];
                assert_eq!(linear_u8(&dim.stride), stride, "{}: layer stride", param.id);
                for pair in starts.windows(2) {
                    assert_eq!(pair[1] - pair[0], stride, "layer grid must be uniform");
                }
            }
            // Set-list steps are 32 sibling rows in one block, not a repeated
            // child: the grid is the distance between "Step 1 Kit" and
            // "Step 2 Kit", and the count is how many such rows the doc has.
            "step" => {
                let rows = m["blocks"]["SetListParams"]["params"].as_array().unwrap();
                let step_row = |n: u32| {
                    rows.iter()
                        .find(|r| r["name"] == format!("Step {n} Kit"))
                        .unwrap_or_else(|| panic!("no 'Step {n} Kit' row in the doc"))
                };
                let stride = linear(step_row(2)["offset"].as_array().unwrap())
                    - linear(step_row(1)["offset"].as_array().unwrap());
                assert_eq!(linear_u8(&dim.stride), stride, "{}: step stride", param.id);
                let documented = rows
                    .iter()
                    .filter(|r| {
                        r["name"]
                            .as_str()
                            .is_some_and(|n| n.starts_with("Step ") && n.ends_with(" Kit"))
                    })
                    .count();
                assert_eq!(
                    dim.count as usize, documented,
                    "{}: step count differs from the doc",
                    param.id
                );
                // The last step must land inside the block.
                let last =
                    linear(step_row(dim.count)["offset"].as_array().unwrap()) + param.len as u64;
                let total = linear(
                    m["blocks"]["SetListParams"]["total_size"]
                        .as_array()
                        .unwrap(),
                );
                assert!(last <= total, "{}: steps overrun the block", param.id);
            }
            other => panic!("{}: unknown dim {other}", param.id),
        }
    }

    // A display offset is presentation, but it must still match the doc: the
    // value column counts from 0, the display column from 1.
    if param.display_offset != 0 {
        let display = mp["display"]
            .as_array()
            .unwrap_or_else(|| panic!("{}: display_offset but no doc display", param.id))
            .iter()
            .filter_map(|d| d.as_str())
            .collect::<Vec<_>>()
            .join(" ");
        let highest = display
            .split(|c: char| !c.is_ascii_digit())
            .filter_map(|t| t.parse::<i64>().ok())
            .max()
            .unwrap_or_else(|| panic!("{}: no numbers in the doc display", param.id));
        let range = param.range.expect("display_offset implies a range");
        assert_eq!(
            highest,
            range.max + param.display_offset,
            "{}: the doc's display column disagrees with display_offset",
            param.id
        );
    }
}

#[test]
fn sub_name_is_64_chars_per_the_doc() {
    // The original hand-authored V31 profile said 16; the parsed doc says 64.
    let p = profile_of(&TARGETS[0]);
    assert_eq!(p.parameter("kit.common.sub_name").unwrap().len, 64);
}

/// The doc's display column sometimes names a value before the numbers — `-INF`
/// under the lowest level, `END` before the first kit of a set-list step. Such a
/// value is not a quantity, and the profile must say so with a `sentinel` at that
/// end of the range: spoken as a number, −601 would become "−60.1 dB", a lie the
/// user cannot see through. The converse holds too: a sentinel the doc does not
/// list is invented.
///
/// Returns the named value when `display` has the shape `NAME, <numeric range>`
/// (footnote markers like `(*2)` dropped). An enum's list (`THRU, EQUALIZER, …`)
/// and a notation like `L30 - 1, CTR, R1 - 30` do not match: their second part
/// is not a number.
fn named_floor(display: &str) -> Option<String> {
    let (head, tail) = display.split_once(',')?;
    let head = head.split('(').next()?.trim();
    let is_number = |s: &str| {
        s.trim_start_matches(['-', '+'])
            .starts_with(|c: char| c.is_ascii_digit())
    };
    (!head.is_empty() && !head.contains(' ') && !is_number(head) && is_number(tail.trim()))
        .then(|| head.to_string())
}

#[test]
fn named_doc_values_are_sentinels_in_the_profile() {
    for t in TARGETS {
        let p = profile_of(t);
        let m = map_of(t);
        let mut sentinels = 0;

        for param in &p.parameters {
            let (block, name) = param.doc.as_deref().unwrap().split_once('/').unwrap();
            let display = map_param(&m, block, name)["display"]
                .as_array()
                .map(|d| {
                    d.iter()
                        .filter_map(Value::as_str)
                        .collect::<Vec<_>>()
                        .join(" ")
                })
                .unwrap_or_default();

            match (&param.sentinel, named_floor(&display)) {
                (Some(sentinel), Some(word)) => {
                    let range = param.range.expect("a sentinel needs a range");
                    assert_eq!(
                        sentinel.raw, range.min,
                        "{}: the doc lists {word} first, so the sentinel is the range minimum",
                        param.id
                    );
                    sentinels += 1;
                }
                (None, Some(word)) => panic!(
                    "{}: the doc lists {word} before the numbers, but the profile has no \
                     sentinel — the value would be spoken as a number",
                    param.id
                ),
                // The parser lost the display column for a few TD-17 rows (the
                // reverb level among them): the range still starts at the
                // family floor, and that floor is -INF on every level the doc
                // does show. A sentinel there is the doc's claim, not ours.
                (Some(sentinel), None) if display.trim().is_empty() => {
                    let range = param.range.expect("a sentinel needs a range");
                    assert_eq!(
                        sentinel.raw, range.min,
                        "{}: sentinel at the floor",
                        param.id
                    );
                    sentinels += 1;
                }
                (Some(sentinel), None) => panic!(
                    "{}: sentinel {} is not in the doc's display column {display:?}",
                    param.id, sentinel.raw
                ),
                (None, None) => {}
            }
        }
        assert!(
            sentinels >= t.min_sentinels,
            "{}: expected at least {} sentinels, found {sentinels}",
            p.profile_id,
            t.min_sentinels
        );
    }
}

/// A `catalog` binding must name a catalog the profile ships, and a
/// `catalog_bank` a parameter that sits next to it — same area, same repeat grid
/// — so the bank read at the instrument's indices is that instrument's own.
#[test]
fn catalog_bindings_resolve() {
    for t in TARGETS {
        let p = profile_of(t);
        let mut bound = 0;

        for param in &p.parameters {
            if let Some(catalog) = &param.catalog {
                assert!(
                    p.catalogs.contains_key(catalog),
                    "{}: catalog {catalog:?} is not in the profile's catalogs",
                    param.id
                );
                bound += 1;
            }
            if let Some(bank_id) = &param.catalog_bank {
                assert!(
                    param.catalog.is_some(),
                    "{}: a bank without a catalog",
                    param.id
                );
                let bank = p.parameter(bank_id).unwrap_or_else(|| {
                    panic!("{}: catalog_bank {bank_id:?} is not a parameter", param.id)
                });
                assert_eq!(
                    bank.area, param.area,
                    "{}: the bank lives in another area",
                    param.id
                );
                assert_eq!(
                    bank.dims.len(),
                    param.dims.len(),
                    "{}: the bank repeats differently",
                    param.id
                );
                for (a, b) in bank.dims.iter().zip(&param.dims) {
                    assert_eq!(
                        (&a.name, a.count, &a.stride),
                        (&b.name, b.count, &b.stride),
                        "{}: dim grid",
                        param.id
                    );
                }
            }
        }
        assert!(
            bound >= t.min_catalog_bindings,
            "{}: expected at least {} catalog bindings, found {bound}",
            p.profile_id,
            t.min_catalog_bindings
        );
    }
}
